### PR TITLE
Fix netmiko driver save_config/commit

### PR DESCRIPTION
**Pull request by rhwendt**
The problem with the current commit/save_config is that every device class in netmiko inherits BaseConnection which defines both a `commit` and `save_config`. Its up to child classes to implement these.  The problem is that since its using an if/elif statement the `save_config` method never gets called for device that have implemented it (NXOS, IOS, etc).

The change here just catches the exception if the netmiko device class doesn't implement `commit` then tries to run `save_config` 

These changes work fine on live devices (IOSXR, NXOS) but the pytests would fail all the time. I spent a long time on it and it seems pytest will fail when it tries to `save_config`. Not really sure why its failing on that but as a fix I changed the uri's to  `/setconfig/dry-run` for the tests which bypasses these save functions. Tests pass now but just wanted to let you know.

### CODE REVIEW

**Comment by tbotnz** [comment]
cheers @rhwendt for the PR, my apologies for the delay in responding on here. I'm a little concerned with why the tests wouldnt past (it makes me think the setconfig route may be broken all together by these changes when using netmiko) but i also see you've changed cisshgo version aswell

I will try and get it tested in the next week to see whats up

thanks for the patience

**Comment by rhwendt** [comment]
Im pretty sure its because the cisshgo app cant handle the `wr mem` or `copy run start` commands even after adding them. Its definitely something with setconfig though Im not quite sure what it is.  I have been using my forked changes for weeks on our project and there are no issues with `setconfig` on netmiko that I have run into at least. If i get some free time I can dig into a little more.

**Comment by wrgeorge1983** [comment]
@tbotnz @rhwendt is this still open and needing work?  If so I can take a crack at this.  Fixing issues identified w/ tests and merging in more recent changes and such.

**Comment by rhwendt** [comment]
Yeah i think it needs more work on the tests side of it. I've been using this for months on my fork on our production gear without issue. Something about this change causes the checks to fail.

**Comment by rhwendt** [comment]
I just realized i snuck a commit in there you guys probably dont want. The one that disables TLS on redis.

**Comment by wrgeorge1983** [comment]
Merged recent changes in and have been digging into this.  this is the crux of the issue: 

```

worker-fifo_1         | [2021-12-05 00:39:39,396:netmiko:send_config_set:DEBUG] cisshgo1000v#configure terminal
worker-fifo_1         | cisshgo1000v(config)#
worker-fifo_1         | cisshgo1000v(config)#cisshgo1000v(config)#hostname CISSHGO1000V885
worker-fifo_1         | CISSHGO1000V885(config)#
worker-fifo_1         | CISSHGO1000V885(config)#end
worker-fifo_1         | CISSHGO1000V885#
worker-fifo_1         |
worker-fifo_1         | [2021-12-05 00:39:39,396:netmiko:_write_channel:DEBUG] write_channel: b'\r\n'
worker-fifo_1         | [2021-12-05 00:39:39,396:netmiko:_read_channel_expect:DEBUG] Pattern is: cisshgo1000v
cisgo_1               | 2021/12/05 00:39:39
cisgo_1               | 2021/12/05 00:39:39
worker-fifo_1         | [2021-12-05 00:39:39,396:netmiko:_read_channel_expect:DEBUG] _read_channel_expect read_data:
worker-fifo_1         | CISSHGO1000V885#
worker-fifo_1         | CISSHGO1000V885#
worker-fifo_1         | [2021-12-05 00:39:39,407:netmiko:_read_channel_expect:DEBUG] _read_channel_expect read_data:
worker-fifo_1         | CISSHGO1000V885#
worker-fifo_1         | CISSHGO1000V885#
```
Netmiko sends the config to change the hostname, and then stalls because it's still waiting for the old hostname in it's expect string.  

ugh.

**Comment by wrgeorge1983** [comment]
Because of the behavior @rhwendt described, it seems the code for `save_config` has been broken for a very long time.  "ever" possibly.  Fixing the flow he found has exposed the following:

if you use the `save_config()` method of `CiscoIOSBaseConnection` (or any that inherit from it) it will call `.enable()` which calls `.check_enable_mode()` which calls `.read_until_prompt()` which finally calls `.read_channel_expect()` and since these methods don't pass down a pattern, `.read_channel_expect()` does this: 
```python
    def _read_channel_expect(self, pattern="", re_flags=0, max_loops=150):
        """Function that reads channel until pattern is detected.

        pattern takes a regular expression.

        By default pattern will be self.base_prompt
       ...
    """
```
and of course `.base_prompt` is set during session initialization and not reset in any way when we change the hostname.

**Comment by wrgeorge1983** [comment]
@tbotnz this should be good to merge now.  Fix was simple once the issue was understood:  just call `.set_base_prompt()` before `.save_config()` in the netmiko driver.  

the integration tests are good as-is, and unit test just needed a tweak.

**Pull request merged**
